operaciones:
  api:
    urlBase: http://172.17.254.17/web-services-seta-apostar/api
    recargas:
      urlBase: /recarga
      urlRecargar: /recargar
      urlConsultarSubproducto: /consultar-subproductos
    betplay:
      urlBase: /betplay
      urlBetPlay: /asdasd
      urlDos: /ased
    recaudos:
      urlBase: /recaudo
      urlConsultarDepartamentos: /consultar-departamentos
      urlConsultarRecaudos: /consultar-recaudos
    sorteos:
      urlBase: /resultado-sorteos
      urlConsultarResultados : /consultar-resultado-sorteos
      urlConsultarResultadosSemanal : /consultar-resultado-sorteos-semanal
distribuidor:
  identificador: 901047246
  usuario-id: 901047246
  cliente-id: 98647142
  equipo-cliente-id: 1256
  llave: MIIBUDCB6AYHKoZIzjgEATCB3AJhAOnmQlmdNV83yX/9NWcSC44lyc1D6SezqWcPvsXYkBQZItLDs60kgAk3mYadHoRqq0n6sK0m0s5qIiGdRwvOfXd9SiH76cJwtX9gcALzzvg5NpTPRe42iMEajFarEno9rwIVAJzb2EyfGsLzjQ+A9Cq5Uuczi/URAmAwRwrVoAX7FM4tnc2
  clave: 123456

server:
  servlet:
    context-path: /dostf-apostar
  port: 5000

