operaciones:
  api:
    urlBase: http://172.17.254.17/web-services-seta-apostar/api
    recargas:
      urlBase: /recarga
      urlRecargar: /recargar

server:
  servlet:
    context-path: /dostf-apostar
  port: 5000

