operaciones:
  api:
    urlBase: http://172.17.254.17/web-services-seta-apostar/api
    recargas:
      urlBase: /recarga
      urlRecargar: /recargar
    betplay:
      urlBase: /betplay
      urlBetPlay: /asdasd
      urlDos: /ased
distribuidor:
  identificador: identificador
  usuarioId: usuarioId
  clienteId: clienteId
  equipoClienteId: equipoClienteId
  llave: llave
  clave: clave

server:
  servlet:
    context-path: /dostf-apostar
  port: 5000

